apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginx-exam
  name: nginx-exam
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-exam
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx-exam
    spec:
      containers:
      - image: nginx:1.18
        name: nginx
        resources: {}
status: {}
