apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: nginx-exam
  labels:
    service: nginx
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nginx-exam
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 3
      maxUnavailable: 2
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx-exam
        type: webshop
    spec:
      containers:
      - image: nginx:1.18
        name: nginx
        resources: {}
status: {}
